cu_cp:
  amf:
    addr: 127.0.0.5
    bind_addr: 127.0.0.1
    supported_tracking_areas:
      - tac: 1
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1

cu_up:
  ngu:
    socket:
      - bind_addr: 127.0.0.1

ru_sdr:
  device_driver: uhd
  device_args: "addr=192.168.50.10,master_clock_rate=23.04e6"
  srate: 23.04
  tx_gain: 50
  rx_gain: 40

cell_cfg:
  pci: 1
  dl_arfcn: 368500
  band: 3
  common_scs: 15
  channel_bandwidth_MHz: 10
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  plmn: "00101"
  tac: 1

log:
  all_level: info
